package dev.audiobook.platform.narration;

public enum NarrationRejectionReason {
    IDEMPOTENCY_KEY_REUSED,
    CONVERSION_VERSION_MISMATCH,
    GENERATION_RECIPE_ALREADY_CONFIRMED,
    VOICE_TEMPORARILY_UNAVAILABLE,
    VOICE_RETIRED,
    UNISSUED_VOICE_IDENTIFIER,
    VOICE_MAPPING_UNAVAILABLE,
    VOICE_MAPPING_STALE,
    CAPABILITY_PROFILE_STALE,
    UNSUPPORTED_REGION_OR_DATA_POLICY,
    UNSUPPORTED_NARRATION_PACE,
    AUDIOBOOK_CONVERSION_NOT_FOUND,
    GENERATION_RECIPE_REQUIRED,
    EXPLICIT_NEW_CHOICE_REQUIRED
}
